services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_UMBRACO_URL: ${PUBLIC_UMBRACO_URL}
    container_name: hjem-i-kroppen-frontend
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
